#!/bin/bash

tmp=$(cat Makefile | head -n 2 | tail -n 1 | cut -f 1 -d ' ' --complement)
clang++ -MJ compile_commands.json $tmp > /dev/null 2>&1
printf "[%s]" "$(cat compile_commands.json)" > compile_commands.json
